# -------------------------------------------------------------------------------
# Site settings
# -------------------------------------------------------------------------------
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "CEFET++"

description:
  en: "Competitive programming team from CEFET-MG (Divinópolis, Brazil)"
  pt_BR: "Equipe de programação competitiva do CEFET-MG (Divinópolis, Brasil)"

url: "https://githubplusplus.orcslab.github.io/"

github:
  url: "https://github.com/cefetplusplus"

author:
  name: "André L. Maravilha"
  email: "andre.maravilha@cefetmg.br"


# -------------------------------------------------------------------------------
# Build settings
# -------------------------------------------------------------------------------

include: 
  - .htaccess

sass:
  sass_dir: assets/stylesheets

plugins:
  - jekyll-feed
  - jekyll-polyglot
  - jekyll-paginate
  - jekyll-node-module

# jekyll-polyglot settings
languages: ["pt_BR", "en"]
default_lang: "pt_BR"
exclude_from_localization: ["assets"]
lang_from_path: true
parallel_localization: false

# jekyll-paginate settings
paginate: 10
paginate_path: "/news/:num"

# jekyll-node-modules settings
node_modules:
  assets:
    js: assets/js
    css: assets/css
  copy:
  - source: "@fortawesome/fontawesome-free/webfonts"
    target: "assets/webfonts"
  - source: "bootstrap-icons/font/fonts"
    target: "assets/css/fonts"
  - source: "academicons/fonts"
    target: "assets/fonts"


# -------------------------------------------------------------------------------
# Exclude from processing
# -------------------------------------------------------------------------------
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/
