# -------------------------------------------------------------------------------
# Site settings
# -------------------------------------------------------------------------------
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "CEFET++"

author: "André L. Maravilha"
email: "andre.maravilha@cefetmg.br"

description: >- 
  Site do CEFET++, equipe de competição em maratonas de programação do CEFET-MG (Campus Divinópolis).

baseurl: ""
url: "https://githubplusplus.orcslab.github.io/"

github_url:  "https://github.com/cefetplusplus"


# -------------------------------------------------------------------------------
# Build settings
# -------------------------------------------------------------------------------

include: 
  - .htaccess

sass:
  sass_dir: assets/stylesheets

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-node-module

node_modules:
  assets:
    js: assets/js
    css: assets/css
  copy:
  - source: "@fortawesome/fontawesome-free/webfonts"
    target: "assets/webfonts"
  - source: "bootstrap-icons/font/fonts"
    target: "assets/css/fonts"
  - source: "academicons/fonts"
    target: "assets/fonts"

paginate: 10
paginate_path: "/news/:num"


# -------------------------------------------------------------------------------
# Exclude from processing
# -------------------------------------------------------------------------------
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - workflows/
