name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.4.2
        
      - name: Install NPM dependencies 🔧
        run: |
          npm install

      - name: Build 🚀
        uses: actions/jekyll-build-page@1.0.5

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: _site
